-Output variable -> y

y -> Whether the client has subscribed a term deposit or not 
Binomial ("yes" or "no")

In [12]:
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt

In [13]:
data = pd.read_csv('bank-full.csv',sep=';')       # sep use for delimiters

In [14]:
data

age           job   marital  education default  balance housing loan  \
0       58    management   married   tertiary      no     2143     yes   no   
1       44    technician    single  secondary      no       29     yes   no   
2       33  entrepreneur   married  secondary      no        2     yes  yes   
3       47   blue-collar   married    unknown      no     1506     yes   no   
4       33       unknown    single    unknown      no        1      no   no   
...    ...           ...       ...        ...     ...      ...     ...  ...   
45206   51    technician   married   tertiary      no      825      no   no   
45207   71       retired  divorced    primary      no     1729      no   no   
45208   72       retired   married  secondary      no     5715      no   no   
45209   57   blue-collar   married  secondary      no      668      no   no   
45210   37  entrepreneur   married  secondary      no     2971      no   no   

         contact  day month  duration  campaign  pdays  previous poutcome    y  
0        unknown    5   may       261         1     -1         0  unknown   no  
1        unknown    5   may       151         1     -1         0  unknown   no  
2        unknown    5   may        76         1     -1         0  unknown   no  
3        unknown    5   may        92         1     -1         0  unknown   no  
4        unknown    5   may       198         1     -1         0  unknown   no  
...          ...  ...   ...       ...       ...    ...       ...      ...  ...  
45206   cellular   17   nov       977         3     -1         0  unknown  yes  
45207   cellular   17   nov       456         2     -1         0  unknown  yes  
45208   cellular   17   nov      1127         5    184         3  success  yes  
45209  telephone   17   nov       508         4     -1         0  unknown   no  
45210   cellular   17   nov       361         2    188        11    other   no  

[45211 rows x 17 columns]

# EDA

In [15]:
data.shape

(45211, 17)

In [16]:
type(data)

pandas.core.frame.DataFrame

In [17]:
# drop unwanted columns
data=data.drop(['job','age','marital','education','balance','contact','day','month','duration','poutcome'],axis=1)

In [18]:
data

default housing loan  campaign  pdays  previous    y
0          no     yes   no         1     -1         0   no
1          no     yes   no         1     -1         0   no
2          no     yes  yes         1     -1         0   no
3          no     yes   no         1     -1         0   no
4          no      no   no         1     -1         0   no
...       ...     ...  ...       ...    ...       ...  ...
45206      no      no   no         3     -1         0  yes
45207      no      no   no         2     -1         0  yes
45208      no      no   no         5    184         3  yes
45209      no      no   no         4     -1         0   no
45210      no      no   no         2    188        11   no

[45211 rows x 7 columns]

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   default   45211 non-null  object
 1   housing   45211 non-null  object
 2   loan      45211 non-null  object
 3   campaign  45211 non-null  int64 
 4   pdays     45211 non-null  int64 
 5   previous  45211 non-null  int64 
 6   y         45211 non-null  object
dtypes: int64(3), object(4)
memory usage: 2.4+ MB


# encoding

In [20]:
from sklearn.preprocessing import LabelEncoder

In [21]:
encoder=LabelEncoder()

In [22]:
data['default']=encoder.fit_transform(data['default'])

In [23]:
data['loan'].unique()

array(['no', 'yes'], dtype=object)

In [24]:
data['housing']=encoder.fit_transform(data['housing'])

In [25]:
data['loan']=encoder.fit_transform(data['loan'])

In [26]:
data['y']=encoder.fit_transform(data['y'])

In [27]:
data.head(10)

default  housing  loan  campaign  pdays  previous  y
0        0        1     0         1     -1         0  0
1        0        1     0         1     -1         0  0
2        0        1     1         1     -1         0  0
3        0        1     0         1     -1         0  0
4        0        0     0         1     -1         0  0
5        0        1     0         1     -1         0  0
6        0        1     1         1     -1         0  0
7        1        1     0         1     -1         0  0
8        0        1     0         1     -1         0  0
9        0        1     0         1     -1         0  0

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   default   45211 non-null  int32
 1   housing   45211 non-null  int32
 2   loan      45211 non-null  int32
 3   campaign  45211 non-null  int64
 4   pdays     45211 non-null  int64
 5   previous  45211 non-null  int64
 6   y         45211 non-null  int32
dtypes: int32(4), int64(3)
memory usage: 1.7 MB


In [29]:
data.describe()

default       housing          loan      campaign         pdays  \
count  45211.000000  45211.000000  45211.000000  45211.000000  45211.000000   
mean       0.018027      0.555838      0.160226      2.763841     40.197828   
std        0.133049      0.496878      0.366820      3.098021    100.128746   
min        0.000000      0.000000      0.000000      1.000000     -1.000000   
25%        0.000000      0.000000      0.000000      1.000000     -1.000000   
50%        0.000000      1.000000      0.000000      2.000000     -1.000000   
75%        0.000000      1.000000      0.000000      3.000000     -1.000000   
max        1.000000      1.000000      1.000000     63.000000    871.000000   

           previous             y  
count  45211.000000  45211.000000  
mean       0.580323      0.116985  
std        2.303441      0.321406  
min        0.000000      0.000000  
25%        0.000000      0.000000  
50%        0.000000      0.000000  
75%        0.000000      0.000000  
max      275.000000      1.000000

In [30]:
data.corr()

default   housing      loan  campaign     pdays  previous         y
default   1.000000 -0.006025  0.077234  0.016822 -0.029979 -0.018329 -0.022419
housing  -0.006025  1.000000  0.041323 -0.023599  0.124178  0.037076 -0.139173
loan      0.077234  0.041323  1.000000  0.009980 -0.022754 -0.011043 -0.068185
campaign  0.016822 -0.023599  0.009980  1.000000 -0.088628 -0.032855 -0.073172
pdays    -0.029979  0.124178 -0.022754 -0.088628  1.000000  0.454820  0.103621
previous -0.018329  0.037076 -0.011043 -0.032855  0.454820  1.000000  0.093236
y        -0.022419 -0.139173 -0.068185 -0.073172  0.103621  0.093236  1.000000

In [31]:
data.isnull().sum()

default     0
housing     0
loan        0
campaign    0
pdays       0
previous    0
y           0
dtype: int64

# Model

In [32]:
X = data.iloc[:,:6]
X

default  housing  loan  campaign  pdays  previous
0            0        1     0         1     -1         0
1            0        1     0         1     -1         0
2            0        1     1         1     -1         0
3            0        1     0         1     -1         0
4            0        0     0         1     -1         0
...        ...      ...   ...       ...    ...       ...
45206        0        0     0         3     -1         0
45207        0        0     0         2     -1         0
45208        0        0     0         5    184         3
45209        0        0     0         4     -1         0
45210        0        0     0         2    188        11

[45211 rows x 6 columns]

In [33]:
y=data.iloc[:,6]
y

0        0
1        0
2        0
3        0
4        0
        ..
45206    1
45207    1
45208    1
45209    0
45210    0
Name: y, Length: 45211, dtype: int32

In [34]:
y.value_counts() 

0    39922
1     5289
Name: y, dtype: int64

# Now deal with Imbalanced data with SMOTE

- SMOTE stands for Synthetic Minority Oversampling Technique.This is a statistical technique for increasing the number of cases in your dataset in a balanced way.The module works by generating new unstances from existing minority cases that you suppy as input.

In [35]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [52]:
import numpy as np
y_train.value_counts()

0    27953
1     3694
Name: y, dtype: int64

In [37]:
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression(random_state=0)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [38]:
# Confusion Matrix for the model accuracy
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
confusion_matrix = confusion_matrix(y_test,y_pred)
print (classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.88      1.00      0.94     11969
           1       0.47      0.01      0.01      1595

    accuracy                           0.88     13564
   macro avg       0.68      0.50      0.47     13564
weighted avg       0.83      0.88      0.83     13564



In [ ]:
# here recall value for 1 is 0.01 which is very less.now apply SMOTE for updating this value

In [39]:
from imblearn.over_sampling import SMOTE
sm=SMOTE(random_state=42)
X_res,y_res=sm.fit_resample(X_train, y_train)

In [53]:
y_res.value_counts()

0    27953
1    27953
Name: y, dtype: int64

In [41]:
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression(random_state=0)
clf.fit(X_res,y_res)
y_pred1=clf.predict(X_test)
y_pred1

array([0, 0, 0, ..., 0, 0, 0])

In [42]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
confusion_matrix = confusion_matrix(y_test,y_pred1)
print (classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.93      0.64      0.75     11969
           1       0.19      0.63      0.29      1595

    accuracy                           0.64     13564
   macro avg       0.56      0.63      0.52     13564
weighted avg       0.84      0.64      0.70     13564



- from above we can clearly see that using Smote technique we increase the f1 score value from 0.01 to 0.29

In [43]:
#now find out probability of predicted 0's and 1's
clf.predict_proba(X)[0]

array([0.61310435, 0.38689565])

In [44]:
y_pred_df= pd.DataFrame({'actual': y,
                         'predicted': clf.predict(X),
                        'p_0': [n[0] for n in clf.predict_proba(X)],
                        'p_1': [n[1] for n in clf.predict_proba(X)]})

In [45]:
y_pred_df

actual  predicted       p_0       p_1
0           0          0  0.613104  0.386896
1           0          0  0.613104  0.386896
2           0          0  0.780625  0.219375
3           0          0  0.613104  0.386896
4           0          1  0.344801  0.655199
...       ...        ...       ...       ...
45206       1          1  0.407656  0.592344
45207       1          1  0.375705  0.624295
45208       1          1  0.353877  0.646123
45209       0          1  0.440408  0.559592
45210       0          1  0.196420  0.803580

[45211 rows x 4 columns]

In [54]:
# Confusion Matrix for the model accuracy
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test,y_pred)
print (confusion_matrix)

[[11960     9]
 [ 1587     8]]


In [56]:
#accuracy
((11960 +8)/(11960 +9+1587+8))*100

88.2335594219994

In [57]:
# ROC Curve
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

fpr, tpr, thresholds = roc_curve(y, clf.predict_proba (X)[:,1])

auc = roc_auc_score(y_test, y_pred1)

import matplotlib.pyplot as plt
plt.plot(fpr, tpr, color='red')
plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel('False Positive Rate or [1 - True Negative Rate]')
plt.ylabel('True Positive Rate')
print('auc accuracy:',auc)


auc accuracy: 0.6324917478826573


In [58]:
fpr

array([0.00000000e+00, 2.50488452e-05, 2.50488452e-05, ...,
       9.99699414e-01, 9.99749512e-01, 1.00000000e+00])

In [59]:
thresholds

array([1.99999868e+00, 9.99998682e-01, 9.24568495e-01, ...,
       2.93936309e-03, 2.24919631e-03, 1.54054530e-04])

In [60]:
tpr

array([0.00000000e+00, 0.00000000e+00, 3.78143316e-04, ...,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00])